<?xml version="1.0" encoding="UTF-8"?>
<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Runtime dependencies. -->
  <ItemGroup>
  </ItemGroup>

  <!-- Development dependencies. -->
  <ItemGroup>
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="[1.2.25]" />
    <PackageVersion Include="Microsoft.DotNet.ApiCompat.Task" Version="[9.0.304]" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="[17.14.1]" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="[17.14.15]" />
  </ItemGroup>

</Project>
